import type { ProductToolDescriptor } from "@my-agent-team/agent-backend";
import type { Tool, ToolExecuteResult } from "@my-agent-team/core";

/** Identity carried on every Product Tool call so the Product backend can
 *  attribute, authorize, and durably record the exchange. Generated by the
 *  Worker from the run snapshot + metadata - never by the caller. */
export interface ProductToolCallIdentity {
  readonly runId: string;
  readonly conversationId: string;
  readonly agentMemberId: string;
  readonly branchId: string;
  readonly callId: string;
}

/** Caller that reaches the Product backend's tool endpoint over MCP (or any
 *  transport). Injectable so the identity/timeout/abort logic is testable
 *  without a live MCP server. */
export interface ProductToolCaller {
  callTool(params: {
    readonly name: string;
    readonly arguments?: unknown;
    readonly identity: ProductToolCallIdentity;
    readonly signal?: AbortSignal;
  }): Promise<{ content: unknown }>;
}

export interface ProductToolTransportOptions {
  readonly identity: Omit<ProductToolCallIdentity, "callId">;
  readonly caller: ProductToolCaller;
  /** Per-call timeout. The run's AbortSignal is forwarded regardless. */
  readonly timeoutMs: number;
}

/** A monotonically-increasing callId keeps each Product Tool exchange
 *  idempotent per run even under concurrent tool batching. */
function callIdSeq(): () => string {
  let n = 0;
  return () => `pt-${++n}`;
}

/** Adapt one Product Tool descriptor into a `Tool`. Its execute forwards the
 *  run AbortSignal + identity + a per-call timeout to the caller. */
export function adaptProductTool(
  descriptor: ProductToolDescriptor,
  opts: ProductToolTransportOptions,
  nextCallId: () => string,
): Tool {
  return {
    name: descriptor.name,
    description: descriptor.description,
    inputSchema: descriptor.inputSchema,
    async execute(input: unknown, signal?: AbortSignal): Promise<ToolExecuteResult> {
      const identity: ProductToolCallIdentity = { ...opts.identity, callId: nextCallId() };
      try {
        const result = await callWithTimeout(
          opts.caller.callTool({ name: descriptor.name, arguments: input, identity, signal }),
          opts.timeoutMs,
          signal,
        );
        return {
          content:
            typeof result.content === "string" ? result.content : JSON.stringify(result.content),
        };
      } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        return { content: message, isError: true };
      }
    },
  };
}

/** Build the Product Tools from a run's manifest. Returns core `Tool[]` (the
 *  Worker casts them into its plugin shape). An empty manifest yields no tools. */
export function buildProductTools(
  productTools: readonly ProductToolDescriptor[],
  opts: ProductToolTransportOptions,
): Tool[] {
  const nextCallId = callIdSeq();
  return productTools.map((d) => adaptProductTool(d, opts, nextCallId));
}

/** Race a promise against a timeout, also rejecting early if the run's
 *  AbortSignal fires. Keeps Product Tool calls bounded by both wall time and
 *  run cancellation. */
async function callWithTimeout<T>(
  promise: Promise<T>,
  timeoutMs: number,
  signal?: AbortSignal,
): Promise<T> {
  return Promise.race([
    promise,
    new Promise<T>((_, reject) => {
      const timer = setTimeout(
        () => reject(new Error(`product tool timed out after ${timeoutMs}ms`)),
        timeoutMs,
      );
      signal?.addEventListener(
        "abort",
        () => {
          clearTimeout(timer);
          reject(new Error("product tool aborted by run stop"));
        },
        { once: true },
      );
    }),
  ]);
}
