import {
  appendFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

/** The oma's own session store (ADR 0003 decision 6): parentId-
 *  chained JSONL, same shape family as pi/omp. The CLI owns its session;
 *  the product stores only the session id (branch.cliSessionRef).
 *
 *  Typing: the wire contract (agent-backend transport) deliberately models
 *  messages as `Record<string, unknown>` - the durable file keeps that same
 *  wire-loose shape. Strict `Message` typing is the runtime's job, applied
 *  where the loop consumes them, so this module performs no type bypass. */

export function sessionDir(): string {
  return process.env.OMA_SESSION_DIR ?? join(homedir(), ".oma", "sessions");
}

export function sessionPath(id: string): string {
  return join(sessionDir(), `${id}.jsonl`);
}

export function newSessionId(): string {
  return crypto.randomUUID();
}

/** Load the transcript messages of a session file (wire-loose shape).
 *  Missing/corrupt files yield [] (the caller falls back to a fresh
 *  session). A compaction event REPLACES everything recorded before it:
 *  the summary becomes one context message, later turns stay live — so a
 *  resumed session does not re-inflate the context it already compacted. */
export function loadSessionMessages(id: string): Record<string, unknown>[] {
  const path = sessionPath(id);
  if (!existsSync(path)) return [];
  const messages: Record<string, unknown>[] = [];
  for (const line of readFileSync(path, "utf8").split("\n")) {
    if (!line.trim()) continue;
    try {
      // The one unavoidable boundary: JSON.parse yields unknown; the typed
      // cast pins OUR durable format's event shape.
      const evt = JSON.parse(line) as {
        type?: string;
        message?: Record<string, unknown>;
        summary?: string;
      };
      if (evt.type === "message" && evt.message?.role) messages.push(evt.message);
      else if (evt.type === "compaction" && typeof evt.summary === "string") {
        messages.length = 0;
        messages.push({
          role: "user",
          text: `<previous_session_summary>\n${evt.summary}\n</previous_session_summary>`,
        });
      }
    } catch {
      /* skip malformed line */
    }
  }
  return messages;
}

export interface SessionSummary {
  readonly id: string;
  readonly modifiedAt: number;
  /** Auto title from the last completed run's title event, when present. */
  readonly title?: string;
  /** First user message text (truncated), fallback when no title exists. */
  readonly preview: string;
}

/** Available session files, newest first. Corrupt files stay listable
 *  (preview degrades to ""). */
export function listSessions(): SessionSummary[] {
  const dir = sessionDir();
  if (!existsSync(dir)) return [];
  const summaries: SessionSummary[] = [];
  for (const entry of readdirSync(dir)) {
    if (!entry.endsWith(".jsonl")) continue;
    const id = entry.slice(0, -".jsonl".length);
    const path = join(dir, entry);
    let preview = "";
    let title: string | undefined;
    try {
      for (const line of readFileSync(path, "utf8").split("\n")) {
        if (!line.trim()) continue;
        const evt = JSON.parse(line) as {
          type?: string;
          title?: string;
          message?: { role?: string; text?: string };
        };
        if (evt.type === "title" && typeof evt.title === "string") {
          title = evt.title;
          continue;
        }
        if (!preview && evt.type === "message" && evt.message?.role === "user") {
          preview = String(evt.message.text ?? "")
            .replace(/\s+/g, " ")
            .slice(0, 60);
        }
      }
    } catch {
      /* corrupt file: listed with an empty preview */
    }
    const summary: { id: string; modifiedAt: number; preview: string; title?: string } = {
      id,
      modifiedAt: statSync(path).mtimeMs,
      preview,
    };
    if (title !== undefined) summary.title = title;
    summaries.push(summary);
  }
  return summaries.sort((a, b) => b.modifiedAt - a.modifiedAt);
}

/** Append a title event: the session's display title, auto-generated by the
 *  loop after each completed run. Last one wins in listings. */
export function appendSessionTitle(id: string, title: string): void {
  const path = sessionPath(id);
  if (!existsSync(path)) return;
  appendFileSync(
    path,
    `${JSON.stringify({
      type: "title",
      timestamp: new Date().toISOString(),
      title,
    })}\n`,
  );
}
/** Append a compaction event: records that the run compacted everything
 *  recorded so far in this file into `summary`. Must be called AFTER the
 *  turn's messages are appended. */
export function appendSessionCompaction(id: string, summary: string): void {
  const path = sessionPath(id);
  if (!existsSync(path)) return;
  appendFileSync(
    path,
    `${JSON.stringify({
      type: "compaction",
      timestamp: new Date().toISOString(),
      summary,
    })}\n`,
  );
}
/** Append message events to the session file (header written on create;
 *  parentId chains to the file's last message id). The tail scan keeps a
 *  per-process lastId cache — resume reads the file once, steady-state
 *  appends are O(1) instead of re-reading the whole transcript. */
const lastIdBySession = new Map<string, string | null>();

function readLastMessageId(path: string): string | null {
  let prevId: string | null = null;
  for (const line of readFileSync(path, "utf8").split("\n").reverse()) {
    if (!line.trim()) continue;
    try {
      const evt = JSON.parse(line) as { type?: string; id?: string };
      if (evt.type === "message" && evt.id) {
        prevId = evt.id;
        break;
      }
    } catch {
      /* skip */
    }
  }
  return prevId;
}

export function appendSessionMessages(id: string, cwd: string, messages: readonly unknown[]): void {
  const dir = sessionDir();
  mkdirSync(dir, { recursive: true });
  const path = sessionPath(id);
  if (!existsSync(path)) {
    writeFileSync(
      path,
      `${JSON.stringify({
        type: "session",
        version: 3,
        id,
        timestamp: new Date().toISOString(),
        cwd,
      })}\n`,
    );
  }
  // First append this process: scan the tail once. Later appends reuse the
  // cached leaf id (one Runtime appends at most once per turn, sequentially).
  if (!lastIdBySession.has(id)) {
    lastIdBySession.set(id, readLastMessageId(path));
  }
  let prevId = lastIdBySession.get(id) ?? null;
  const lines: string[] = [];
  for (const message of messages) {
    const eventId = crypto.randomUUID();
    lines.push(
      JSON.stringify({
        type: "message",
        id: eventId,
        parentId: prevId,
        timestamp: new Date().toISOString(),
        message,
      }),
    );
    prevId = eventId;
  }
  lastIdBySession.set(id, prevId);
  appendFileSync(path, `${lines.join("\n")}\n`);
}
