import type { ProductToolDescriptor } from "@my-agent-team/agent-backend";
import type { Tool, ToolExecuteResult } from "@my-agent-team/core";

/** Identity carried on every Product Tool call so the Product backend can
 *  attribute, authorize, and durably record the exchange. Generated by the
 *  Worker from the run snapshot + metadata - never by the caller. */
export interface ProductToolCallIdentity {
  readonly runId: string;
  readonly conversationId: string;
  readonly agentMemberId: string;
  readonly branchId: string;
  readonly callId: string;
  /** Stable per-run idempotency key for the Product Backend
   *  (`${runId}:${callId}`). callId is monotonic per run, so retries within
   *  the run replay; a fresh run produces fresh keys. */
  readonly idempotencyKey: string;
}

/** Caller that reaches the Product backend's tool endpoint over MCP (or any
 *  transport). Injectable so the identity/timeout/abort logic is testable
 *  without a live MCP server. */
export interface ProductToolCaller {
  callTool(params: {
    /** MCP tool name (descriptor.name). */
    readonly name: string;
    /** MCP server address (descriptor.entrypoint) - the transport binding. */
    readonly entrypoint: string;
    readonly arguments?: unknown;
    readonly identity: ProductToolCallIdentity;
    readonly signal?: AbortSignal;
  }): Promise<{ content: unknown }>;
}

export interface ProductToolTransportOptions {
  readonly identity: Omit<ProductToolCallIdentity, "callId" | "idempotencyKey">;
  readonly caller: ProductToolCaller;
  /** Per-call timeout. The run's AbortSignal is forwarded regardless. */
  readonly timeoutMs: number;
}

/** A monotonically-increasing callId keeps each Product Tool exchange
 *  idempotent per run even under concurrent tool batching. */
function callIdSeq(): () => string {
  let n = 0;
  return () => `pt-${++n}`;
}

/** Adapt one Product Tool descriptor into a `Tool`. Its execute forwards the
 *  run AbortSignal + identity + a per-call timeout to the caller. */
export function adaptProductTool(
  descriptor: ProductToolDescriptor,
  opts: ProductToolTransportOptions,
  nextCallId: () => string,
): Tool {
  return {
    name: descriptor.name,
    description: descriptor.description,
    inputSchema: descriptor.inputSchema,
    async execute(
      input: unknown,
      signal?: AbortSignal,
      options?: { callId?: string },
    ): Promise<ToolExecuteResult> {
      // The model tool-use id (PendingToolCall.id) when the loop supplies it:
      // stable under same-semantics replays, unlike an order-dependent
      // counter. The counter is only the fallback for direct/caller-driven
      // executions that carry no model identity.
      const callId = options?.callId ?? nextCallId();
      const identity: ProductToolCallIdentity = {
        ...opts.identity,
        callId,
        idempotencyKey: `${opts.identity.runId}:${callId}`,
      };
      // A per-call controller lets BOTH the run's stop signal and the timeout
      // abort the underlying MCP request (the caller tears its transport down).
      const controller = new AbortController();
      const onRunAbort = () => controller.abort();
      signal?.addEventListener("abort", onRunAbort, { once: true });
      try {
        const result = await callWithTimeout(
          opts.caller.callTool({
            name: descriptor.name,
            entrypoint: descriptor.entrypoint,
            arguments: input,
            identity,
            signal: controller.signal,
          }),
          opts.timeoutMs,
          controller.signal,
          () => controller.abort(),
        );
        return {
          content:
            typeof result.content === "string" ? result.content : JSON.stringify(result.content),
        };
      } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        return { content: message, isError: true };
      } finally {
        signal?.removeEventListener("abort", onRunAbort);
      }
    },
  };
}

/** Build the Product Tools from a run's manifest. Returns core `Tool[]` (the
 *  Worker casts them into its plugin shape). An empty manifest yields no tools. */
export function buildProductTools(
  productTools: readonly ProductToolDescriptor[],
  opts: ProductToolTransportOptions,
): Tool[] {
  const nextCallId = callIdSeq();
  return productTools.map((d) => adaptProductTool(d, opts, nextCallId));
}

/** Race a promise against a timeout, also rejecting early if the run's
 *  AbortSignal fires. Keeps Product Tool calls bounded by both wall time and
 *  run cancellation. `onCancel` lets the caller tear down the underlying
 *  transport so a timed-out/aborted MCP request actually dies instead of
 *  producing a side effect after the caller moved on. All timers and abort
 *  listeners are cleaned up on settle. */
async function callWithTimeout<T>(
  promise: Promise<T>,
  timeoutMs: number,
  signal?: AbortSignal,
  onCancel?: () => void,
): Promise<T> {
  let timer: Timer | undefined;
  let rejectTimeout!: (err: Error) => void;
  const timeoutPromise = new Promise<T>((_, reject) => {
    rejectTimeout = reject;
  });
  const abort = (message: string): void => {
    if (timer) {
      clearTimeout(timer);
      timer = undefined;
    }
    // Remove the listener BEFORE onCancel: onCancel may abort the signal this
    // listens on, which must not re-trigger with a different message.
    signal?.removeEventListener("abort", abortListener);
    onCancel?.();
    rejectTimeout(new Error(message));
  };
  const abortListener = () => abort("product tool aborted by run stop");
  signal?.addEventListener("abort", abortListener, { once: true });
  try {
    timer = setTimeout(() => abort(`product tool timed out after ${timeoutMs}ms`), timeoutMs);
    return await Promise.race([promise, timeoutPromise]);
  } finally {
    clearTimeout(timer);
    signal?.removeEventListener("abort", abortListener);
  }
}
