import type { Message } from "@my-agent-team/message";
import type { BackendModelRef } from "./model.js";

/** A projected history entry. `productEntryId` is the stable Agent Context
 *  entry identity, retained so the Runtime can write it onto its appended
 *  entries and never persist the same canonical Message twice. It is not a
 *  Runtime message ID and must not be regenerated by the Runtime. */
export interface ProjectedHistoryItem {
  readonly productEntryId: string;
  readonly message: Message;
}

/** Runtime-accessible workspace and its permission boundary. */
export interface WorkspaceBinding {
  readonly root: string;
  readonly access: "read_only" | "read_write";
}

/** Product Tool manifest entry exposed to a Backend. */
export interface ProductToolDescriptor {
  readonly name: string;
  readonly description: string;
  readonly inputSchema: Readonly<Record<string, unknown>>;
  readonly entrypoint: string;
}

/** Frozen per-Run configuration. Fixed at Agent Run start; every `execute()`
 *  carries it so model, system prompt and Product Tool manifest changes take
 *  effect on the next Run without any shared state. Parameterized by `K` so
 *  the model ref's backendKind is locked to the Backend's kind. */
export interface AgentRunSnapshot<K extends string = string> {
  readonly runId: string;
  readonly model: BackendModelRef<K>;
  readonly systemPrompt?: string;
  readonly productTools: readonly ProductToolDescriptor[];
  readonly configRevision: number;
}
