import type { Message } from "@my-agent-team/message";
import type { BackendEvent, Usage } from "./event.js";
import type { AgentRunSnapshot, ProjectedHistoryItem, WorkspaceBinding } from "./history.js";

/** The actual execution input crossing the Backend boundary: the durable
 *  Product input-queue identity plus the canonical Message it carries.
 *
 *  - `inputId` is generated by the Product Backend's durable input queue and
 *    is the stable idempotency source for every mutation that submits this
 *    input. The Adapter/Daemon MUST NOT regenerate it.
 *  - `message` is the canonical Message (user/steer/follow-up). It is the sole
 *    "actual prompt" - the Backend never infers a prompt from history and never
 *    fabricates placeholder text.
 *  - `productEntryId` is set when this input has already produced an Agent
 *    Context entry; the Runtime writes it onto the prompt/steer/follow-up entry
 *    it appends, so the same canonical Message is never persisted twice. */
export interface BackendInputMessage {
  readonly inputId: string;
  readonly message: Message;
  readonly productEntryId?: string;
}

/** Input for creating or resuming an execution session. `start()` and
 *  `resume()` both receive the full snapshot, the projected history, and the
 *  actual input Message that drives this Run. Parameterized by `K` so the
 *  snapshot's model ref is locked to the Backend's kind. */
export interface BackendStartInput<K extends string = string> {
  readonly history: readonly ProjectedHistoryItem[];
  readonly input: BackendInputMessage;
  readonly run: AgentRunSnapshot<K>;
  readonly workspace: WorkspaceBinding;
  readonly metadata: {
    readonly conversationId: string;
    readonly agentMemberId: string;
    readonly branchId: string;
    readonly productRevision: number;
  };
}

/** Input for continuing an existing execution session. `history` is the
 *  projected context (renamed from `messages` so context is never confused
 *  with the driving input); `input` is the actual Message for this turn.
 *  `run` is required so model/prompt/tool changes apply on the next Run without
 *  a rebuild. Parameterized by `K` so the snapshot's model ref matches the
 *  Backend's kind. */
export interface BackendRunInput<K extends string = string> {
  readonly history: readonly ProjectedHistoryItem[];
  readonly input: BackendInputMessage;
  readonly run: AgentRunSnapshot<K>;
  readonly mode: "normal" | "steer" | "follow_up";
  readonly metadata: {
    readonly branchId: string;
    readonly throughEntryId?: string;
    readonly productRevision: number;
  };
}

/** Execution session reference - the plain identity Product Backend holds for
 *  an open session. It carries only `backendSessionId` and `backendKind`; it is
 *  intentionally not an opaque/unforgeable token. The adapter looks up live
 *  state (client, process, connection) by `backendSessionId` in its own
 *  registry. Lifecycle (open/closed) is NOT a snapshot on this immutable ref -
 *  it belongs to the execution layer and the adapter's live session registry. */
export interface BackendSessionRef<K extends string = string> {
  readonly backendSessionId: string;
  readonly backendKind: K;
}

/** A pending approval, question or permission request awaiting a product
 *  control-plane response. */
export interface PendingAction {
  readonly actionId: string;
  readonly kind: string;
  readonly payload: Readonly<Record<string, unknown>>;
}

/** Structured response to a PendingAction. Carries `actionId` for idempotency;
 *  each actionId is consumed at most once. */
export interface PendingActionResponse {
  readonly actionId: string;
  readonly response: unknown;
}

/** Terminal outcome of a run segment. `completed`, `failed`, `aborted` and
 *  `timeout` are Agent Run terminal states. `suspended` is nonterminal: the
 *  Agent Run retains its branch lock and active-run identity, awaiting a
 *  PendingActionResponse. This is the ONLY terminal authority - event streams
 *  must not be interpreted as terminal. */
export type BackendRunOutcome =
  | { readonly status: "completed"; readonly output?: Message; readonly usage?: Usage }
  | { readonly status: "suspended"; readonly pendingAction: PendingAction; readonly usage?: Usage }
  | {
      readonly status: "failed" | "aborted" | "timeout";
      readonly error?: string;
      readonly usage?: Usage;
    };

/** A single run continuation: an event stream plus a terminal outcome promise.
 *  `stop()` requests cancellation; the outcome still resolves. Parameterized by
 *  `K` so events are namespaced to the Backend's kind. */
export interface BackendRunSegment<K extends string = string> {
  readonly events: AsyncIterable<BackendEvent<K>>;
  readonly outcome: Promise<BackendRunOutcome>;
  stop(): Promise<void>;
}

/** A started/resumed session: the session ref and the first run segment.
 *  Returning the first segment alongside the ref avoids a cold-start requiring
 *  an extra `send()` before execution begins. */
export interface BackendSessionRun<
  K extends string = string,
  TRef extends BackendSessionRef<K> = BackendSessionRef<K>,
> {
  readonly session: TRef;
  readonly segment: BackendRunSegment<K>;
}
