import type { Message } from "@my-agent-team/message";
import type { BackendEvent, Usage } from "./event.js";
import type { AgentRunSnapshot, WorkspaceBinding } from "./history.js";

/** The actual execution input crossing the Backend boundary: the durable
 *  Product input-queue identity plus the canonical Message it carries.
 *
 *  - `inputId` is generated by the Product Backend's durable input queue and
 *    is the stable idempotency source for every mutation that submits this
 *    input. The Adapter/child MUST NOT regenerate it.
 *  - `message` is the canonical Message (user/steer/follow-up). It is the sole
 *    "actual prompt" - the Backend never infers a prompt from history and never
 *    fabricates placeholder text.
 *  - `productEntryId` is set when this input has already produced an Agent
 *    Context entry; the Runtime writes it onto the prompt/steer/follow-up entry
 *    it appends, so the same canonical Message is never persisted twice. */
export interface BackendInputMessage {
  readonly inputId: string;
  readonly message: Message;
  readonly productEntryId?: string;
}

/** The complete durable facts of one Agent Run crossing the Backend boundary.
 *  History is NOT part of the contract (ADR 0003 decision 6): the first-turn
 *  bridge is flat text inside `input.message` (rendered by the Backend when
 *  the branch has no CLI session reference yet); from the second turn on the
 *  CLI session is the runtime truth. `workspace` is a Run execution fact (the
 *  caller pins the cloned repo for Loop Runs, the agent-record workspace
 *  otherwise), never re-derived by the Backend. Parameterized by `K` so the
 *  snapshot's model ref is locked to the Backend's kind. */
export interface BackendRunInput<K extends string = string> {
  readonly input: BackendInputMessage;
  readonly run: AgentRunSnapshot<K>;
  readonly workspace: WorkspaceBinding;
  /** Per-run product-tools bearer. Backends deliver it to their child
   *  (spawn env). Absent = no product tools for this run. */
  readonly productToolsToken?: string;
  readonly metadata: {
    readonly conversationId: string;
    readonly agentMemberId: string;
    readonly branchId: string;
  };
}

/** A pending approval, question or permission request awaiting a product
 *  control-plane response. Product-side record; not part of the Run protocol. */
export interface PendingAction {
  readonly actionId: string;
  readonly kind: string;
  readonly payload: Readonly<Record<string, unknown>>;
}

/** Structured response to a PendingAction. Carries `actionId` for idempotency;
 *  each actionId is consumed at most once. */
export interface PendingActionResponse {
  readonly actionId: string;
  readonly response: unknown;
}

/** Terminal outcome of a Run. `completed`, `failed`, `aborted` and `timeout`
 *  are the four terminal states. This is the ONLY terminal authority - event
 *  streams must never be interpreted as terminal.
 *
 *  A completed Run carries the full canonical message sequence it produced
 *  (ADR 0017): assistant(tool_use) / tool(tool_result) / assistant(text) as
 *  separate messages, in order, ready to be persisted and replayed. The
 *  final answer is the last assistant message with text. */
export type BackendRunOutcome =
  | {
      readonly status: "completed";
      readonly messages?: readonly Message[];
      readonly usage?: Usage;
      readonly title?: string;
      /** CLI-side session reference (ADR 0002): claude session_id or a
       *  pi/omp session file path. Product Backend persists it on the
       *  branch (agent_context_branch.cli_session_ref) as the runtime
       *  truth for context continuation. */
      readonly cliSessionRef?: string;
    }
  | {
      readonly status: "failed" | "aborted" | "timeout";
      readonly error?: string;
      readonly usage?: Usage;
      readonly cliSessionRef?: string;
    };

/** A single run segment: an event stream plus a terminal outcome promise.
 *  `stop()` requests cancellation; the outcome still resolves. Parameterized by
 *  `K` so events are namespaced to the Backend's kind. */
export interface BackendRunSegment<K extends string = string> {
  readonly events: AsyncIterable<BackendEvent<K>>;
  readonly outcome: Promise<BackendRunOutcome>;
  stop(): Promise<void>;
}
